language: node_js
node_js:
  - "8.11.1"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $night
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: dev

